### ISSUE TITLE
problema com o teste 

### ISSUE THREAD

**Issue by diegolpes77** [ProfRonan/gerenciador-de-tarefas-diegolpes77#2]
enquanto estava fazendo a atividade, fui testar e não estava rodando na atividade de gerenciador de tarefas

**Comment by SeuRonao** [comment]
Vou precisar de mais informações sobre o que está acontecendo, tem como mandar um screenshot ou algo parecido?

**Comment by diegolpes77** [comment]
ok, ai está, há um tempo que quero concluir ela porem acontece isso

![Captura de tela 2023-06-18 171818](https://github.com/ProfRonan/gerenciador-de-tarefas-diegolpes77/assets/129468376/2b376a63-0da7-4ded-af7f-a60325892a85)

**Comment by diegolpes77** [comment]
Eu não consegui. Parei ai

**Comment by SeuRonao** [comment]
Quando não conseguir, é melhor não fechar a issue.
Assim fica organizado mostrando que o problema ainda persiste.
Faça um commit com a versão mais recente que esse problema aparece, por favor.

**Comment by diegolpes77** [comment]
Ok, irei fazer ainda hj

**Comment by SeuRonao** [comment]
#1 Atualizei os arquivos, faça um git pull quando for trabalhar nisso.
